externalHostname: ''
mongo:
  image:
    repository: mongo
    tag: 7.0.28
  port: 27001
  replicaSet: rs0
  persistence:
    size: 10Gi
    storageClass: ''
redis:
  image:
    repository: redis/redis-stack-server
    tag: 7.2.0-v6
  port: 6379
  maxMemory: 256mb
  persistence:
    size: 5Gi
    storageClass: ''
minio:
  image:
    repository: minio/minio
    tag: RELEASE.2024-07-04T14-25-45Z
  port: 9000
  webPort: 9001
  bucket: minio-bucket
  accessKey: minio_access_key
  secretKey: minio_secret_key
  persistence:
    size: 120Gi
    storageClass: ''
coordinator:
  image:
    repository: ghcr.io/anyproto/any-sync-coordinator
    tag: latest
  port: 1004
  quicPort: 1014
  nodePort: 30004
  quicNodePort: 30014
  limits:
    spaceMembersRead: 1000
    spaceMembersWrite: 1000
    sharedSpacesLimit: 1000
  resources:
    limits:
      memory: 1.5Gi
    requests:
      memory: 1.5Gi
  persistence:
    size: 1Gi
    storageClass: ''
filenode:
  image:
    repository: ghcr.io/anyproto/any-sync-filenode
    tag: latest
  port: 1005
  quicPort: 1015
  nodePort: 30005
  quicNodePort: 30015
  defaultLimit: 107374182400
  resources:
    limits:
      memory: 1.5Gi
    requests:
      memory: 1.5Gi
  persistence:
    size: 120Gi
    storageClass: ''
syncNode1:
  image:
    repository: ghcr.io/anyproto/any-sync-node
    tag: latest
  port: 1001
  quicPort: 1011
  nodePort: 30001
  quicNodePort: 30011
  resources:
    limits:
      memory: 1.5Gi
    requests:
      memory: 1.5Gi
  persistence:
    size: 10Gi
    storageClass: ''
syncNode2:
  image:
    repository: ghcr.io/anyproto/any-sync-node
    tag: latest
  port: 1002
  quicPort: 1012
  nodePort: 30002
  quicNodePort: 30012
  resources:
    limits:
      memory: 1.5Gi
    requests:
      memory: 1.5Gi
  persistence:
    size: 10Gi
    storageClass: ''
syncNode3:
  image:
    repository: ghcr.io/anyproto/any-sync-node
    tag: latest
  port: 1003
  quicPort: 1013
  nodePort: 30003
  quicNodePort: 30013
  resources:
    limits:
      memory: 1.5Gi
    requests:
      memory: 1.5Gi
  persistence:
    size: 10Gi
    storageClass: ''
consensusnode:
  image:
    repository: ghcr.io/anyproto/any-sync-consensusnode
    tag: latest
  port: 1006
  quicPort: 1016
  nodePort: 30006
  quicNodePort: 30016
  resources:
    limits:
      memory: 1.5Gi
    requests:
      memory: 1.5Gi
  persistence:
    size: 1Gi
    storageClass: ''
netcheck:
  image:
    repository: ghcr.io/anyproto/any-sync-tools
    tag: latest
  enabled: true
init:
  image:
    repository: ghcr.io/anyproto/any-sync-tools
    tag: latest
coordinatorBootstrap:
  image:
    repository: ghcr.io/anyproto/any-sync-coordinator
    tag: latest
createBucket:
  image:
    repository: minio/mc
    tag: latest
exportClientConfig:
  image:
    repository: bitnami/kubectl
    tag: latest
