apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: any-sync-node-1
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
  name: any-sync-node-1
spec:
  ports:
  - name: '1001'
    port: 1001
    targetPort: 1001
  - name: '1011'
    port: 1011
    protocol: UDP
    targetPort: 1011
  - name: '8081'
    port: 8081
    targetPort: 8080
  - name: '8001'
    port: 8001
    targetPort: 8000
  selector:
    io.kompose.service: any-sync-node-1
