apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: any-sync-node-3-claim1
  name: any-sync-node-3-claim1
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
