apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: any-sync-coordinator
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
  name: any-sync-coordinator
spec:
  ports:
  - name: coordinator-tcp
    port: {{ .Values.coordinator.port }}
    targetPort: {{ .Values.coordinator.port }}
    nodePort: {{ .Values.coordinator.nodePort }}
  - name: coordinator-quic
    port: {{ .Values.coordinator.quicPort }}
    protocol: UDP
    targetPort: {{ .Values.coordinator.quicPort }}
    nodePort: {{ .Values.coordinator.quicNodePort }}
  - name: '8004'
    port: 8004
    targetPort: 8000
  selector:
    app.kubernetes.io/name: any-sync-coordinator
    app.kubernetes.io/instance: '{{ .Release.Name }}'
  type: NodePort
