apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: any-sync-node-2
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
  name: any-sync-node-2
spec:
  ports:
  - name: syncnode2-tcp
    port: {{ .Values.syncNode2.port }}
    targetPort: {{ .Values.syncNode2.port }}
    nodePort: {{ .Values.syncNode2.nodePort }}
  - name: syncnode2-quic
    port: {{ .Values.syncNode2.quicPort }}
    protocol: UDP
    targetPort: {{ .Values.syncNode2.quicPort }}
    nodePort: {{ .Values.syncNode2.quicNodePort }}
  - name: '8082'
    port: 8082
    targetPort: 8080
  - name: '8002'
    port: 8002
    targetPort: 8000
  selector:
    app.kubernetes.io/name: any-sync-node-2
    app.kubernetes.io/instance: '{{ .Release.Name }}'
  type: NodePort
