apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: any-sync-coordinator
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
  name: any-sync-coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: any-sync-coordinator
      app.kubernetes.io/instance: '{{ .Release.Name }}'
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: any-sync-coordinator
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    spec:
      containers:
      - image: '{{ .Values.coordinator.image.repository }}:{{ .Values.coordinator.image.tag }}'
        name: any-sync-coordinator
        ports:
        - containerPort: {{ .Values.coordinator.port }}
          protocol: TCP
        - containerPort: {{ .Values.coordinator.quicPort }}
          protocol: UDP
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            memory: '{{ .Values.coordinator.resources.limits.memory }}'
          requests:
            memory: '{{ .Values.coordinator.resources.requests.memory }}'
        volumeMounts:
        - mountPath: /etc/any-sync-coordinator/config.yml
          name: network-configs
          subPath: coordinator.yml
        - name: network-configs
          mountPath: /etc/any-sync-coordinator/network.yml
          subPath: network.yml
        - mountPath: /networkStore
          name: any-sync-coordinator-claim1
      restartPolicy: Always
      volumes:
      - name: any-sync-coordinator-claim1
        persistentVolumeClaim:
          claimName: any-sync-coordinator-claim1
      - name: network-configs
        secret:
          secretName: '{{ include "any-sync.fullname" . }}-network-configs'
