apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: any-sync-node-3
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
  name: any-sync-node-3
spec:
  ports:
  - name: syncnode3-tcp
    port: {{ .Values.syncNode3.port }}
    targetPort: {{ .Values.syncNode3.port }}
    nodePort: {{ .Values.syncNode3.nodePort }}
  - name: syncnode3-quic
    port: {{ .Values.syncNode3.quicPort }}
    protocol: UDP
    targetPort: {{ .Values.syncNode3.quicPort }}
    nodePort: {{ .Values.syncNode3.quicNodePort }}
  - name: '8083'
    port: 8083
    targetPort: 8080
  - name: '8003'
    port: 8003
    targetPort: 8000
  selector:
    app.kubernetes.io/name: any-sync-node-3
    app.kubernetes.io/instance: '{{ .Release.Name }}'
  type: NodePort
