apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: any-sync-filenode
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
  name: any-sync-filenode
spec:
  ports:
  - name: filenode-tcp
    port: {{ .Values.filenode.port }}
    targetPort: {{ .Values.filenode.port }}
    nodePort: {{ .Values.filenode.nodePort }}
  - name: filenode-quic
    port: {{ .Values.filenode.quicPort }}
    protocol: UDP
    targetPort: {{ .Values.filenode.quicPort }}
    nodePort: {{ .Values.filenode.quicNodePort }}
  - name: '8005'
    port: 8005
    targetPort: 8000
  selector:
    io.kompose.service: any-sync-filenode
  type: NodePort
