apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: any-sync-consensusnode
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
  name: any-sync-consensusnode
spec:
  ports:
  - name: consensusnode-tcp
    port: '{{ .Values.consensusnode.port }}'
    targetPort: '{{ .Values.consensusnode.port }}'
    nodePort: '{{ .Values.consensusnode.nodePort }}'
  - name: consensusnode-quic
    port: '{{ .Values.consensusnode.quicPort }}'
    protocol: UDP
    targetPort: '{{ .Values.consensusnode.quicPort }}'
    nodePort: '{{ .Values.consensusnode.quicNodePort }}'
  - name: '8006'
    port: 8006
    targetPort: 8000
  selector:
    io.kompose.service: any-sync-consensusnode
  type: NodePort
