apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: any-sync-node-2
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
  name: any-sync-node-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: any-sync-node-2
      app.kubernetes.io/instance: '{{ .Release.Name }}'
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: any-sync-node-2
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    spec:
      containers:
      - image: '{{ .Values.syncNode2.image.repository }}:{{ .Values.syncNode2.image.tag }}'
        name: any-sync-node-2
        ports:
        - containerPort: '{{ .Values.syncNode2.port }}'
          protocol: TCP
        - containerPort: '{{ .Values.syncNode2.quicPort }}'
          protocol: UDP
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            memory: '{{ .Values.syncNode2.resources.limits.memory }}'
          requests:
            memory: '{{ .Values.syncNode2.resources.requests.memory }}'
        volumeMounts:
        - mountPath: /etc/any-sync-node/config.yml
          name: network-configs
          subPath: node-2.yml
        - mountPath: /root/.aws/credentials
          name: network-configs
          readOnly: true
          subPath: aws-credentials
        - mountPath: /storage
          name: any-sync-node-2-claim2
        - mountPath: /anyStorage
          name: any-sync-node-2-claim3
        - mountPath: /networkStore
          name: any-sync-node-2-claim4
      restartPolicy: Always
      volumes:
      - name: any-sync-node-2-claim2
        persistentVolumeClaim:
          claimName: any-sync-node-2-claim2
      - name: any-sync-node-2-claim3
        persistentVolumeClaim:
          claimName: any-sync-node-2-claim3
      - name: any-sync-node-2-claim4
        persistentVolumeClaim:
          claimName: any-sync-node-2-claim4
      - name: network-configs
        secret:
          secretName: '{{ include "any-sync.fullname" . }}-network-configs'
