apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: any-sync-node-1
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
  name: any-sync-node-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: any-sync-node-1
      app.kubernetes.io/instance: '{{ .Release.Name }}'
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: any-sync-node-1
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    spec:
      containers:
      - image: '{{ .Values.syncNode1.image.repository }}:{{ .Values.syncNode1.image.tag }}'
        name: any-sync-node-1
        ports:
        - containerPort: '{{ .Values.syncNode1.port }}'
          protocol: TCP
        - containerPort: '{{ .Values.syncNode1.quicPort }}'
          protocol: UDP
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            memory: '{{ .Values.syncNode1.resources.limits.memory }}'
        volumeMounts:
        - mountPath: /etc/any-sync-node
          name: any-sync-node-1-claim0
        - mountPath: /root/.aws
          name: any-sync-node-1-claim1
          readOnly: true
        - mountPath: /storage
          name: any-sync-node-1-claim2
        - mountPath: /anyStorage
          name: any-sync-node-1-claim3
        - mountPath: /networkStore
          name: any-sync-node-1-claim4
      restartPolicy: Always
      volumes:
      - name: any-sync-node-1-claim0
        persistentVolumeClaim:
          claimName: any-sync-node-1-claim0
      - name: any-sync-node-1-claim1
        persistentVolumeClaim:
          claimName: any-sync-node-1-claim1
          readOnly: true
      - name: any-sync-node-1-claim2
        persistentVolumeClaim:
          claimName: any-sync-node-1-claim2
      - name: any-sync-node-1-claim3
        persistentVolumeClaim:
          claimName: any-sync-node-1-claim3
      - name: any-sync-node-1-claim4
        persistentVolumeClaim:
          claimName: any-sync-node-1-claim4
