apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: any-sync-node-2
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
  name: any-sync-node-2
spec:
  ports:
  - name: '1002'
    port: 1002
    targetPort: 1002
  - name: '1012'
    port: 1012
    protocol: UDP
    targetPort: 1012
  - name: '8082'
    port: 8082
    targetPort: 8080
  - name: '8002'
    port: 8002
    targetPort: 8000
  selector:
    io.kompose.service: any-sync-node-2
