{{/*
RBAC for the any-sync-init job to allow it to create the network configuration Secret.
*/}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "any-sync.fullname" . }}-init
  labels:
    {{- include "any-sync.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "any-sync.fullname" . }}-init
  labels:
    {{- include "any-sync.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "any-sync.fullname" . }}-init
  labels:
    {{- include "any-sync.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation
subjects:
  - kind: ServiceAccount
    name: {{ include "any-sync.fullname" . }}-init
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "any-sync.fullname" . }}-init
  apiGroup: rbac.authorization.k8s.io
