apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
  name: redis
spec:
  ports:
  - name: redis-tcp
    port: {{ .Values.redis.port }}
    targetPort: {{ .Values.redis.port }}
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: '{{ .Release.Name }}'
  clusterIP: None
