apiVersion: v1
kind: Secret
metadata:
  name: {{ include "any-sync.fullname" . }}-minio-credentials
  labels:
    {{- include "any-sync.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.minio.accessKey | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.secretKey | quote }}
  credentials: |
    [default]
    aws_access_key_id={{ .Values.minio.accessKey }}
    aws_secret_access_key={{ .Values.minio.secretKey }}
