apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: any-sync-init-claim2
  name: any-sync-init-claim2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
