apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: any-sync-node-2-claim3
  name: any-sync-node-2-claim3
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
