apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: any-sync-consensusnode
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
  name: any-sync-consensusnode
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: any-sync-consensusnode
      app.kubernetes.io/instance: '{{ .Release.Name }}'
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: any-sync-consensusnode
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    spec:
      containers:
      - image: '{{ .Values.consensusnode.image.repository }}:{{ .Values.consensusnode.image.tag }}'
        name: any-sync-consensusnode
        ports:
        - containerPort: '{{ .Values.consensusnode.port }}'
          protocol: TCP
        - containerPort: '{{ .Values.consensusnode.quicPort }}'
          protocol: UDP
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            memory: '{{ .Values.consensusnode.resources.limits.memory }}'
          requests:
            memory: '{{ .Values.consensusnode.resources.requests.memory }}'
        volumeMounts:
        - mountPath: /etc/any-sync-consensusnode/config.yml
          name: network-configs
          subPath: consensusnode.yml
        - mountPath: /networkStore
          name: any-sync-consensusnode-claim1
      restartPolicy: Always
      volumes:
      - name: any-sync-consensusnode-claim1
        persistentVolumeClaim:
          claimName: any-sync-consensusnode-claim1
      - name: network-configs
        secret:
          secretName: '{{ include "any-sync.fullname" . }}-network-configs'
