apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: any-sync-filenode
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
  name: any-sync-filenode
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: any-sync-filenode
      app.kubernetes.io/instance: '{{ .Release.Name }}'
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: any-sync-filenode
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    spec:
      containers:
      - image: '{{ .Values.filenode.image.repository }}:{{ .Values.filenode.image.tag }}'
        name: any-sync-filenode
        ports:
        - containerPort: '{{ .Values.filenode.port }}'
          protocol: TCP
        - containerPort: '{{ .Values.filenode.quicPort }}'
          protocol: UDP
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            memory: '{{ .Values.filenode.resources.limits.memory }}'
          requests:
            memory: '{{ .Values.filenode.resources.requests.memory }}'
        volumeMounts:
        - mountPath: /etc/any-sync-filenode/config.yml
          name: network-configs
          subPath: filenode.yml
        - mountPath: /root/.aws/credentials
          name: network-configs
          readOnly: true
          subPath: aws-credentials
        - mountPath: /networkStore
          name: any-sync-filenode-claim2
      restartPolicy: Always
      volumes:
      - name: any-sync-filenode-claim2
        persistentVolumeClaim:
          claimName: any-sync-filenode-claim2
      - name: network-configs
        secret:
          secretName: '{{ include "any-sync.fullname" . }}-network-configs'
