{{- if eq .Values.ingress.type "traefik" }}
# --- Coordinator QUIC ---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: {{ include "any-sync.fullname" . }}-coordinator-quic
  labels:
    {{- include "any-sync.labels" . | nindent 4 }}
spec:
  entryPoints:
    - any-sync-coordinator-quic
  routes:
    - services:
        - name: any-sync-coordinator
          port: {{ .Values.coordinator.quicPort }}
---
# --- Filenode QUIC ---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: {{ include "any-sync.fullname" . }}-filenode-quic
  labels:
    {{- include "any-sync.labels" . | nindent 4 }}
spec:
  entryPoints:
    - any-sync-filenode-quic
  routes:
    - services:
        - name: any-sync-filenode
          port: {{ .Values.filenode.quicPort }}
---
# --- Consensusnode QUIC ---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: {{ include "any-sync.fullname" . }}-consensusnode-quic
  labels:
    {{- include "any-sync.labels" . | nindent 4 }}
spec:
  entryPoints:
    - any-sync-consensusnode-quic
  routes:
    - services:
        - name: any-sync-consensusnode
          port: {{ .Values.consensusnode.quicPort }}
---
# --- Sync Node 1 QUIC ---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: {{ include "any-sync.fullname" . }}-sync-node-1-quic
  labels:
    {{- include "any-sync.labels" . | nindent 4 }}
spec:
  entryPoints:
    - any-sync-node-1-quic
  routes:
    - services:
        - name: any-sync-node-1
          port: {{ .Values.syncNode1.quicPort }}
---
# --- Sync Node 2 QUIC ---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: {{ include "any-sync.fullname" . }}-sync-node-2-quic
  labels:
    {{- include "any-sync.labels" . | nindent 4 }}
spec:
  entryPoints:
    - any-sync-node-2-quic
  routes:
    - services:
        - name: any-sync-node-2
          port: {{ .Values.syncNode2.quicPort }}
---
# --- Sync Node 3 QUIC ---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: {{ include "any-sync.fullname" . }}-sync-node-3-quic
  labels:
    {{- include "any-sync.labels" . | nindent 4 }}
spec:
  entryPoints:
    - any-sync-node-3-quic
  routes:
    - services:
        - name: any-sync-node-3
          port: {{ .Values.syncNode3.quicPort }}
{{- end }}
